// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloIconify: typeof import('./../src/components/HelloIconify.vue')['default']
    HelloNaiveUi: typeof import('./../src/components/HelloNaiveUi.vue')['default']
    HelloUnocss: typeof import('./../src/components/HelloUnocss.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
  }
}
